### PR TITLE
Add Alfred Maestro

### PR DESCRIPTION
**Pull request by iansinnott**
Alfred integration with [Keyboard Maestro](https://www.keyboardmaestro.com/main/).

### CODE REVIEW

**Comment by derimagia** [comment]
Looks decent, can you rename the link to "Maestro" (Otherwise all of them would be "Alfred X", I'll need to put this in the CONTRIBUTING.md) and then place it in alphabetical order in the group?

**Comment by iansinnott** [comment]
Sure, makes sense, made the update. I renamed it to "keyboard maestro" because "maestro" doesn't sound very descriptive IMO.

**Comment by derimagia** [comment]
Looks good!

**Comment by iansinnott** [comment]
Thanks!

**Pull request merged**
