### PR TITLE
Add Productivity group, move Things to it, and add Google Calendar View

### PR DESCRIPTION
**Pull request by deanishe**
"Productivity" seems like a generally-useful group—it's also one of Alfred's default workflow categories.

I've moved @xilopaint's Things workflow into it (seems a better fit than "Miscellaneous"), and added my new [Google Calendar workflow](https://github.com/deanishe/alfred-gcal) to it.

### CODE REVIEW

**Comment by xilopaint** [comment]
Nice. I think Alfred PDF Tools would be better placed in the new Productivity category as well.

**Comment by derimagia** [comment]
I could see some of the things go both ways (WebScreenshot as well) although it's not as good as a fit. Do you mind splitting it into 2 commits? One for new Productivity Group + things (and whatever other workflows we are moving) and another for your gcal workflow. Same PR is fine.

**Comment by deanishe** [comment]
Done

**Comment by derimagia** [comment]
Perfect. 👍

**Pull request merged**
