### PR TITLE
Add Spotify Mini Player

### PR DESCRIPTION
**Pull request by vdesabou**
More details on this web site http://alfred-spotify-mini-player.com

This is my workflow, but I think very helpful for all Spotify users.

### CODE REVIEW

**Comment by deanishe** [comment]
I've heard very good things about this workflow, and it's very well supported AFAIK.

I'm all for adding it, but I think it would be a good idea to add it to a new "Multimedia" category, rather than to "Web".

I mean, "web" is not one of the first things that pops into your mind when you think of Spotify.

I could add my [mpd workflow](https://github.com/deanishe/alfred-mpd) to make the category less bare for now.

What do you think, @derimagia?

**Comment by derimagia** [comment]
I haven't used it (don't use spotify) but I have seen it around - I noticed before it's actually on Alfred's "official" list https://www.alfredapp.com/workflows.

Multimedia category sounds good to me as well

**Comment by vdesabou** [comment]
Thanks, I've added it under a new Multimedia category

**Comment by derimagia** [comment]
Can you please put the category alphabetically (Under Miscellaneous) and then add a link to it in the Table of Contents? Will merge it after that.

**Pull request merged**
