### PR TITLE
add rxjs workflow

### PR DESCRIPTION
**Pull request by SamVerschueren**
Added the [rxjs](https://github.com/SamVerschueren/alfred-rxjs) workflow.

### CODE REVIEW

**Comment by derimagia** [comment]
Nice work on all these for starters.

A little worried about all of these similar frameworks cluttering it up for people who don't use them. Also if i were to use these I'd want to use Dash so I'm a bit biased. If you can get others to agree this fits I'll merge it.

Related to #20

**Comment by SamVerschueren** [comment]
It's your list, so your call to make :).

I totally understand about the Ionic workflow because that one can easily be done with Dash. Couldn't find this one though through Dash, so not sure if it is there... Also the thing with this workflow, and the Angular workflow are some extra features that aren't possible with dash. For instance, the Angular workflow not only searches the API documentation, but also the entire Angular website. The extra addition with this RxJS workflow is that you can easily copy-paste the import statement that you need in your code. For example, if you search for `Subject` and press <kbd>alt</kbd> + <kbd>enter</kbd>, the following snippet is copied to your clipboard

```js
import { Subject } from 'rxjs/Subject';
```

Or if you are searching for an operator, it will copy this

```js
import 'rxjs/add/operator/mergeMap';
```

But like I said, totally your call to make as it is your list. I wouldn't be angry at all :) :beers:

**Comment by derimagia** [comment]
Going to close these for now but I'm up for others to weigh in on it. One thing I would say a compromise would be is replacing the ng link you have with a link to some page that has all of your misc js framework workflows. Or add it to the bottom - I just don't want to clutter it up. 

Maybe if we get some more frameworks and others like these we can add another section, I'm just not convinced yet! :)

**Comment by SamVerschueren** [comment]
Sure thing. Thanks for your answer @derimagia! Would you merge [alfred-fkill](https://github.com/samverschueren/alfred-fkill) if I did a PR for it?

**Comment by derimagia** [comment]
Yeah I'd merge it. Looks good. One thing I'd say is a packaged app preferred where someone who wasn't a developer could just install it from a file (since this could be useful to others) but I'd still merge it in

**Comment by derimagia** [comment]
Any update on getting this in here?

**Pull request closed without merging**
