### PR TITLE
Add Emoj

### PR DESCRIPTION
**Pull request by sindresorhus**
https://github.com/sindresorhus/alfred-emoj

You can just write some text and it will present relevant emoji by analyzing the text.

### CODE REVIEW

**Comment by derimagia** [comment]
For some reason this isn't quite working with me - node is installed through homebrew at /usr/bin/local/node (Node 5). I'll check later tonight to see if it's something with my machine because I see the issue in npms as well.

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/alfred-emoj/issues/1 Will be fixed as soon as a track down why it doesn't work.

**Comment by derimagia** [comment]
I haven't done alfred workflows yet with node but it may be a good use case for path helper? http://www.softec.lu/site/DevelopersCorner/MasteringThePathHelper - It's at least something I wanted to look more into.

**Comment by sindresorhus** [comment]
@derimagia Thanks for the link. Looks similar to what I'm already doing, but probably handles more edge-cases. I think I'm gonna use both, just to be sure.

**Comment by sindresorhus** [comment]
Should be working now btw. Try version 0.1.1.

**Comment by derimagia** [comment]
Awesome works great - merging this in!

I believe https://github.com/bevesce/unicode-symbols-search works for emojis btw for a comparison.  Still going to accept this because it's specialized and doesn't just use a giant file for it (Even if it's a web service).

One thing that unicode symbols search has though is it shows a description of the item when you search which I would say is a plus. Thanks again for your contribution!

**Comment by sindresorhus** [comment]
> One thing that unicode symbols search has though is it shows a description of the item when you search 

Mine is pretty much the reverse. It takes a description and shows matching emoji.

**Comment by derimagia** [comment]
That is what the other one does as well except it shows the official unicode name though

Example is 🐎  which is "Horse Racing" http://emojipedia.org/horse-racing/. If you search for "horse" this will show up and say "horse racing" even though you only searched for horse.

**Comment by sindresorhus** [comment]
Easier to illustrate with screenshots:

screen shot 2016-06-27 at 00 28 32
screen shot 2016-06-27 at 00 28 40

-

screen shot 2016-06-27 at 00 59 51
screen shot 2016-06-27 at 01 00 05

**Comment by derimagia** [comment]
Yeah I know the difference - you use http://emoji.getdango.com/api/emoji?q=horse which looks like it hooks into the mobile app somehow and gets some crowdsourcing information while uss just searches the official names of the emojis.

 At any rate the way you're querying them isn't the thing I was suggesting - I was just suggesting showing the names of the results and/or the unicode codes (maybe when you press shift or alt if you wanted to keep it clean?) At any rate this wasn't the place for a feature suggestion sorry about that. Thanks again!

**Pull request merged**
